# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170818_0330'),
        ('users', '0010_auto_20161127_2001'),
    ]

    operations = [
    ]
